#!/bin/sh
# Copyright (c) 2022 anatawa12 and other contributors
# This file is part of fixRTM, released under GNU LGPL v3 with few exceptions
# See LICENSE at https://github.com/fixrtm/fixRTM for more details

set -eu

commitlint --edit "$1"
